# springboot
server:
  port: 8888

spring:
  application:
    name: hello-world

mycar:
  price: 100000
  brand: byd

# oss对象存储配置
oss-constant:
  endpoint: secrete
  access-key: key
  secret-key: key
  bucket: bucket