spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/mydatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMutiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver